-- Sadman portfolio backend setup for Supabase
-- Run this ONCE in Supabase Dashboard -> SQL Editor.

create table if not exists public.portfolio_visitors (
  id bigint generated by default as identity primary key,
  visitor_id text not null unique,
  created_at timestamptz not null default now()
);

create table if not exists public.portfolio_signals (
  id bigint generated by default as identity primary key,
  visitor_id text not null unique,
  name varchar(40) not null,
  comment varchar(240),
  created_at timestamptz not null default now()
);

alter table public.portfolio_visitors enable row level security;
alter table public.portfolio_signals enable row level security;

-- Remove old policies safely if rerunning this script.
drop policy if exists "public can count visitors" on public.portfolio_visitors;
drop policy if exists "public can register visitor" on public.portfolio_visitors;
drop policy if exists "public can read signals" on public.portfolio_signals;
drop policy if exists "public can send signal" on public.portfolio_signals;

-- Public site can read rows for counts/feed.
create policy "public can count visitors"
on public.portfolio_visitors
for select
to anon
using (true);

create policy "public can read signals"
on public.portfolio_signals
for select
to anon
using (true);

-- Public site can insert only. Unique visitor_id prevents repeat inflation per browser id.
create policy "public can register visitor"
on public.portfolio_visitors
for insert
to anon
with check (
  char_length(visitor_id) between 10 and 120
);

create policy "public can send signal"
on public.portfolio_signals
for insert
to anon
with check (
  char_length(visitor_id) between 10 and 120
  and char_length(name) between 1 and 40
  and (comment is null or char_length(comment) <= 240)
);

grant select, insert on table public.portfolio_visitors to anon;
grant select, insert on table public.portfolio_signals to anon;
grant usage, select on sequence public.portfolio_visitors_id_seq to anon;
grant usage, select on sequence public.portfolio_signals_id_seq to anon;
